### ISSUE TITLE
UX Improvement: Close folder when name clicked

### ISSUE THREAD

**Issue by micycle1** [KrabCode/LazyGui#226]
One can click on the folder (i.e. background) to open it, but clicking on it again does not close it (as would be intuitive). Consider adding this behaviour.

![image](https://user-images.githubusercontent.com/9304234/229870660-4f323b7d-2e47-49af-a6fe-c0b1436bd3b7.png)

**Comment by wrightwriter** [comment]
yeah, it was like this before, i really like this behaviour as well

**Comment by KrabCode** [comment]
I re-introduced it as an option that is off by default - find it under options/windows/click closes window

**Comment by KrabCode** [comment]
this is in the current 1.0.0 release
![image](https://user-images.githubusercontent.com/25923016/229924660-f970dbff-b6a2-4212-a7cc-2f20850abb16.png)
