### ISSUE TITLE
Snap to grid is off

### ISSUE THREAD

**Issue by micycle1** [KrabCode/LazyGui#229]
Snap to grid is snapping the corner of windows to the middle of grid points, rather than the gridpoints themselves.

**Comment by wrightwriter** [comment]
it's a setting

**Comment by KrabCode** [comment]
a) micycle is describing the current default state - I don't see how this is an issue, you should also specify what you expected in order for us to understand what is wrong

b) let's please be more helpful when responding to people, you could for example point out where they can find this setting with a screenshot

c) you can currently find this setting under `options/grid/points centered`
