### ISSUE TITLE
textSet does not exist?

### ISSUE THREAD

**Issue by dkyy** [KrabCode/LazyGui#258]
I'm trying to set the text of a text field, but am getting a "The function 'textSet( String, String)' does not exist." error.

Here is a code fragment:

```
import com.krab.lazy.*;

LazyGui gui;

void setup() {
  size(1200, 800, P2D);
  gui = new LazyGui(this);
}


void draw() {
  String labelText = gui.text("text1", "editable text");
  textSet( "text1", "abc");
}
```

I've just started using LazyGui and love it, but as I'm new perhaps there's something obvious I'm doing wrong...

Thank you,

david

**Comment by dkyy** [comment]
My mistake. I needed to call it like this:

`gui.textSet
`

**Comment by KrabCode** [comment]
Probably my mistake actually, I didn't have the "gui." part of "gui.textSet" in the README.md - it's fixed now
