### ISSUE TITLE
Request: Functions to create/load saves

### ISSUE THREAD

**Issue by dkyy** [KrabCode/LazyGui#259]
The ability to have "saves" is a great feature of LazyGui. I'd love to be able to generates "saves," and to load saves programmatically (ie. not through the GUI).
For example - I'm using the GUI to adjust parameters which then create an image. When I save that image I'd like to also save a corresponding "save." That way, if I wanted to go back and edit the image I'd just need to load the "save" and go from there.
Ideally I could name the save, as well as save it in an arbitrary director.

For example 

`gui.createSave( "/users/david/project/my_save_name.json");`
and
`gui.loadSave("/users/david/project/my_save_name.json");`

Thanks,

david,

**Comment by KrabCode** [comment]
Great idea, I'll do that, it shouldn't be too difficult. Thanks for the suggestion!

**Comment by KrabCode** [comment]
It turns out that I have no way of telling whether you want to create a local save path in the GUI folder or a global file somewhere else so I split that up into two functions, createSave() and createSaveAbsolute()...

I'm still considering what best to name these new public facing functions and I want to test them a bit, build something with it like your image editing app... I think in a day or two this feature can be released

**Comment by KrabCode** [comment]
Maybe I could auto-detect local/global paths from the presence of slashes and after Paths.get() the slashes should even be the same across operating systems.

I would like it to be intuitive, so I'll try that. The load function already works either way.

**Comment by KrabCode** [comment]
this could help me... 
https://stackoverflow.com/questions/7566071/check-whether-a-path-is-absolute-or-relative

**Comment by dkyy** [comment]
Interesting. I'm running on MacOS, which is basically Unix, so the "/" beginning makes sense. But have no idea about other platforms.
Maybe you don't need two separate functions if you can autodetect.

**Comment by KrabCode** [comment]
I think I figured out the auto-detection with the help of java.nio.file.Paths.get(fileName).isAbsolute();
I tested it a bit and it seems ok. It's released in the current v1.3.0, you're welcome to try it out.
You can see how I tested it here: [SaveFromCodeTest.java](https://github.com/KrabCode/LazyGui/blob/master/src/main/java/com/krab/lazy/examples_intellij/SaveFromCodeTest.java)

There are 3 new functions in the main API: 
  - [createSave()](https://krabcode.github.io/LazyGui/com/krab/lazy/LazyGui.html#createSave())
  - [createSave(path)](https://krabcode.github.io/LazyGui/com/krab/lazy/LazyGui.html#createSave(java.lang.String))
  - [loadSave(path)](https://krabcode.github.io/LazyGui/com/krab/lazy/LazyGui.html#loadSave(java.lang.String))

**Comment by dkyy** [comment]
Works great for me. Thank you for adding this!!
