### ISSUE TITLE
not compatible with PeasyCam library - 3D camera

### ISSUE THREAD

**Issue by trackme518** [KrabCode/LazyGui#271]
Hi, 
the LazyGui interfere with PeasyCam library for 3D camera movement - example code:
```

import com.krab.lazy.*;

LazyGui gui;

import peasy.PeasyCam;
PeasyCam cam;

void setup() {
  size(800, 800, P3D);
  gui = new LazyGui(this);
  cam = new PeasyCam(this, 400);
}

void draw() {

  background(0);
  background(gui.colorPicker("background").hex);

  translate(width/2, height/2, 0);
  //noFill();
  fill(255);
  stroke(255);
  box(200);
}
```
When you manipulate the camera by click and drag mouse left button, the camera rotates correctly but when you release the button it will reset to original position. 

I would suggest adding method to explicitly render the gui at given point in the draw() function - like gui.render(); and in the setup something like gui.renderAutomatically(false); 

That way I can wrap it around PeasyCam methods:

```
  cam.beginHUD();
  //gui.render();
  cam.endHUD();
```

**Comment by KrabCode** [comment]
This should already be possible, please try using `gui.draw()` in place of `gui.render()` in your pseudocode, it could work.

https://krabcode.github.io/LazyGui/com/krab/lazy/LazyGui.html#draw-processing.core.PGraphics-

**Comment by KrabCode** [comment]
Maybe I should make an example that demonstrates working with PeasyCam, it's a pretty popular library.

Internally gui.draw() calls gui.draw(this) so you can just omit the PGraphics parameter. The gui draw duplication in the same frame should already be taken care of by the `lastFrameCountGuiWasShown` variable, so there should be no need to do renderAutomatically(false) in the constructor settings.

See the implementation:
https://github.com/KrabCode/LazyGui/blob/b07c8c0bd3dda8ae23712d78656f692e74319130/src/main/java/com/krab/lazy/LazyGui.java#L172

**Comment by KrabCode** [comment]
I just tested the above solution and it works, but a new problem is that PeasyCam still detects the mouse movements whenever the mouse is inside the GUI, which you probably don't want - dragging a slider should not also rotate the view. 

I found a way to disable that, sadly the PeasyCam method `cam.setMouseControlled()` is deprecated, but it seems to still work well in the current PeasyCam version 302 and gui.isMouseOutsideGui() has the related mouse information we need here.

Example of PeasyCam and LazyGui working together adapted from the HelloPeasy example:

```java
import com.krab.lazy.*;
import peasy.PeasyCam;

PeasyCam cam;
LazyGui gui;

public void settings() {
  size(800, 600, P3D);
}

public void setup() {
  cam = new PeasyCam(this, 400);
  gui = new LazyGui(this);
}

public void draw() {
  rotateX(-.5f);
  rotateY(-.5f);
  lights();
  scale(10);
  strokeWeight(gui.slider("stroke weight", 0.1f));
  background(0);
  
  fill(gui.colorPicker("big box", color(255,0,0)).hex);
  box(30);
  pushMatrix();
  translate(0, 0, 20);
  
  fill(gui.colorPicker("small box", color(0,0,255)).hex);
  box(5);
  popMatrix();

  cam.beginHUD();
  gui.draw();
  cam.endHUD();
  cam.setMouseControlled(gui.isMouseOutsideGui());
}
```

**Comment by trackme518** [comment]
Hi,
I already took care of the problem with dragging when over GUI but your solution is more elegant I think. 

~~~~
  //---------------------------------------
  //prevent interference between GUI and interactive camera
  if (!gui.isMouseOutsideGui() && !guiEntered) {
    cam.setActive(false);
    //camstate = cam.getState();
    guiEntered = true;
    //println("gui enetered");
  }

  if (gui.isMouseOutsideGui() && guiEntered) {
    //cam.setState(camstate);
    guiEntered = false;
    cam.setActive(true);
    //println("gui left");
  }
  //apply camera to offscreen buffer
  cam.getState().apply(pg);
  //----------------------------------------
~~~~

**Comment by trackme518** [comment]
I will test the method with gui.draw() - sorry I didn't realize this method is already there - maybe you can add an example to readme for other people. I the meantime I already implemented drawing the 3d scene to offscreeen buffer and the main draw is left in P2D which "solves" the problem. But I am not sure if it affects performance so the gui.draw() is still useful method to know about.

**Comment by trackme518** [comment]
One slight problem is that the isMouseOutside() method doesn't work properly. When you are outside GUI window and then you move mouse over window title it will not register - but once you move mouse over inside the window (on parameters) it registers the window title area as well properly.

**Comment by KrabCode** [comment]
Okay, if you can reproduce the isMouseOutside problem, please make another issue with just that.

Thanks for bringing all this up, I'll take a look at improving the documentation and examples.

**Comment by trackme518** [comment]
> ```java
>   strokeWeight(gui.slider("stroke weight", 0.1f));
> ```

this works for me
