### ISSUE TITLE
float slider's accuracy changes often

### ISSUE THREAD

**Issue by alexhunsley** [KrabCode/LazyGui#280]
I have some float sliders. On first run, they behave as expected. After a short time of use, they lose accuracy somehow -- becoming very hard to move, or too sensitive.

Is there a workaround I can do for the moment? Like using int sliders then scaling to floats in code? I have a demo I'd love to use LazyGUI for coming up soon.

The issue also happens to the X Y sliders in the Plot component.

When it happens, I have to delete my `auto.json` file and start again in order to get normality back. I will try to do a before/after diff to see if something is odd in the json when it happens.

Is the issue related to this one?
https://github.com/KrabCode/LazyGui/issues

I'm using latest Processing and latest LazyGUI on Mac OS on an M1 MacBook.

**Comment by alexhunsley** [comment]
Here's a screenshot showing a change in the JSON.

On the left is the json as created after my sketch was launched fresh for first time then exited.
On the right is the json saved after the slider precision issue appeared. It does look like precision data is changing in the json when that happens, is this expected?

Cheers!


![Screenshot 2024-02-01 at 17 15 51](https://github.com/KrabCode/LazyGui/assets/793071/7c0835ee-443c-4d3e-bc49-db703e21cae0)

**Comment by KrabCode** [comment]
This might be related to the value, the slider probably ignores the saved precision and uses an estimate of a useful precision for the given value... it shouldn't ignore the saved precision when loaded, that's probably a bug. I'll take a look at it as I solve a related default precision issue soon.

Also as a quick workaround you can change this precision manually using the scroll wheel at runtime with your mouse over the slider. Or by typing a value in there, the precision will adjust to match the value given.

**Comment by alexhunsley** [comment]
Ahhhh mouse wheel! I have a magic mouse on mac and it's probably that! But without any perceptable tactic feedback when the virtual wheel is moving (smoth surface mouse). Please let me confirm.

Is there any way to disable the mouse wheel reactivity in LazyGUI? 

Thanks!

**Comment by alexhunsley** [comment]
Confirmed! It's the magic mouse "wheel". The slightest up/down input on the virtual wheel and the precision just slams intos the big or small end of possible values, due to the sensitivity of the magic mouse. 

I'll have a peruse of the code and try to spot where a flag might be introduced to disable the mouse wheel for a sketch.

**Comment by KrabCode** [comment]
Disabling the wheel with some constructor parameter sounds good and I can code that, but we need some alternative way to change the precision manually... maybe * and / seem the most intuitive, but not everyone has these keys easily accessible. Any hotkey ideas?

**Comment by alexhunsley** [comment]
Hmm good question. I’ll have to have a look at the existing shortcuts to get an idea.Btw have you considered a facility to put optional help text in a control? For mouse over or something similar, so user might see a hint? I just ust had a go at cloning the repo and running in Intellij, but there’s possibly an issue with a dependency:——Build file '/Users/alex.hunsley/Documents/dev/LazyGui/build.gradle' line: 2Plugin [id: 'com.github.johnrengelman.shadow', version: '7.0.0'] was not found in any of the following sources:* Try:> Run with --stacktrace option to get the stack trace.> Run with --info or --debug option to get more log output.> Run with --scan——Some googling shows this dependency seems to come up with issues sometimes, not sure why:https://github.com/johnrengelman/shadow/issues/750Cheers,AlexSent from my iPhoneOn 1 Feb 2024, at 20:44, Jakub Rak ***@***.***> wrote:﻿
Disabling the wheel with a new constructor parameter (LazyGuiSettings) and/or at runtime in the gui hotkey options sounds good and we can introduce that, but we need some alternative way to change the precision manually... maybe * and / seem the most intuitive, but not everyone has these keys easily accessible. Any hotkey ideas?

**Comment by KrabCode** [comment]
Oh, alright, well you can fix the gradle problem by just deleting everything related to the shadow jar plugin, it's only used to publish the jar.

**Comment by KrabCode** [comment]
The mouse wheel can now be disabled in v1.5.0, feel free to try it out.

There was no bug that would cause a saved precision to be ignored, it seems it's not ignored, so that's good.
