### ISSUE TITLE
Suggestion: Alternative colour pickers

### ISSUE THREAD

**Issue by alexhunsley** [KrabCode/LazyGui#281]
Any chance of having an alternative colour picker that is like a palette chooser? Say, like a varying colour square: hue in X direction, brightness going down from centre, and going up to white.

Or maybe even just a palette picker with distinct boxes and colours, just  to help you set the hue slider.

My use case: designers who are used to picking a colour, rather than sliding a hue bar to find it.

Don't mind mucking in to try doing it, if I get project compiling.

**Comment by KrabCode** [comment]
I think the option of pasting a hex code into the hex field already makes the color picker very compatible with various online palette tools...
