### ISSUE TITLE
`isMouseOutsideGui()` doesn't work everywhere

### ISSUE THREAD

**Issue by alexhunsley** [KrabCode/LazyGui#284]
If you mistake e.g. a radio button or a button for a slider, and drag on its label, `gui.isMouseOutsideGui()` returns ~`false`~ sorry I mean `true`.

**Comment by KrabCode** [comment]
I think that's intended? The mouse is inside the gui, regardless of whether it's interacting with a slider or a button or a radio...

Maybe I'm not understanding what you mean.

**Comment by alexhunsley** [comment]
Sorry, I have the bool the wrong way round. I mean that `isMouseOutsideGui()` returns `true` if you drag on a radio button or button lazyGui element (the buttons OR their label), so my gui reposnds to the mouse dragging when it seems like it shouldn't?

**Comment by KrabCode** [comment]
I can reproduce this, thanks. I'll try to fix it.

**Comment by KrabCode** [comment]
fix released in v1.6.0
