### ISSUE TITLE
Missing Setter for radio array option

### ISSUE THREAD

**Issue by trackme518** [KrabCode/LazyGui#285]
Hi,
is it possible to have a setter for radio type controller? I want to refresh the array of options, not to set particular option...
`gui.radioSet("mode", "square");` // setter
will set only particular option
I would like to have something like: 
`gui.radioSet("mode", ArrayList<String>); //to set array options`

**Comment by KrabCode** [comment]
I think I can add that, thanks. Related info in #286

**Comment by KrabCode** [comment]
released in v1.6.0 but it might be buggy, please report any strange behavior and reopen this issue if anything comes up
