### ISSUE TITLE
longer time to change slider number / text - let user set timeout

### ISSUE THREAD

**Issue by trackme518** [KrabCode/LazyGui#287]
Hi,
when typing into slider or text to change the content, the timeout to accept the change is actually quite small - so it happens often that when I am typing number it will change before I am able to type the whole number. Can you make public the method to set the timeout on these changes, and perhaps include it in init settings?

**Comment by KrabCode** [comment]
Alright... that seems reasonable and doable. 

You can already set the timeout inside the options window though. You can even set it using gui.sliderSet() with its actual path as a workaround for now.

**Comment by KrabCode** [comment]
released in v1.6.0

**Comment by trackme518** [comment]
HI, I just tested with 1.8.2

```
  gui = new LazyGui(this, new LazyGuiSettings()
    .setKeyboardDelay(5000)
    .setAutosaveOnExit(true)
    // ...
    );
```

And it did not change the behavior - the input is still considered done after approx 1sec of not typing. 

I am also getting error when typing negative number:
`For input string: "-" java.lang.NumberFormatException: For input string: "-"`

**Comment by trackme518** [comment]
Ok, I just realized that this setting is overridden with previously saved options - so in order for this to be functional one needs to delete previously saved gui saves / options. Make sense
