### ISSUE TITLE
Toggles not centered after resizing GUI

### ISSUE THREAD

**Issue by pfhaupt** [KrabCode/LazyGui#298]
After modifying cell size and font size using the options in the GUI, toggles are no longer centered
![image](https://github.com/KrabCode/LazyGui/assets/41621734/b656c355-9ad0-4022-8a21-68350c628bfd)

**Comment by KrabCode** [comment]
just tested it, can't reproduce - the text is what is not centered and there's nothing I can do about that - there's already a "y offset" slider right next to the font size sliders - adjust that to see everything line up

![image](https://github.com/KrabCode/LazyGui/assets/25923016/71d7feea-ec13-4dca-931d-30de79548031)

**Comment by pfhaupt** [comment]
![image](https://github.com/KrabCode/LazyGui/assets/41621734/0bdbd422-7ac3-44a4-a447-8578854afd65)
After checking again, it was indeed the text that was not centered, `y offset` fixed that, thanks! :^)
