### ISSUE TITLE
Precision lost when manually typing 5+ decimals or starting with a minus

### ISSUE THREAD

**Issue by trackme518** [KrabCode/LazyGui#304]
Hi, 
it seems the precision is not respected when typing manually into the slider ( it works when selected with mouse-wheel). I can change the precision inside the saved settings thought. But I would expect that the precision should automatically increase when I type longer number?

https://github.com/KrabCode/LazyGui/assets/50262885/e68ed24b-4ecb-4828-93fd-6aafbcece351

**Comment by KrabCode** [comment]
This should automatically set the precision but maybe the problem here is that you're trying to use more decimals than we can represent - I bet it works if you just use 4 decimals.

I'll take a look at this edge case when you input more than 4 decimals, it should set the highest available precision.

**Comment by trackme518** [comment]
This is my definition for the slider:
`PVector bottomLeft = new PVector( gui.slider("area coords/bottomLeft/lat", 32.888635), gui.slider("area coords/bottomLeft/long", -96.595225) );`

Note that in both cases I am setting precision to 6 decimal spaces but it is not respected in case of the negative number. I need those 6 decimal places as it is a difference between precision in kilometers and few centimeters in case of GPS coordinates - 4 places is sadly just not enough. I might get around this by using string input I guess. But I bet there will be more people who would like to have more precise sliders than 4 decimals.

**Comment by trackme518** [comment]
[1.json](https://github.com/KrabCode/LazyGui/files/15483032/1.json)
This is my settings when saved doing no edits - with given definition of the slider. You can see that internally the value is preserved but strangely in GUI the negative number shows as Int. But the positive values is showed with decimal places.

**Comment by KrabCode** [comment]
this will be fixed soon in v1.8.3
